[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#39BDF8"
backgroundColor = "#07111F"
secondaryBackgroundColor = "#0D1A2C"
textColor = "#E7EEF8"
font = "sans serif"
